import {StyleSheet} from 'react-native';
import {Colors} from './Colors';

export const alertStyles = StyleSheet.create({
  mainOuterComponent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mainContainer: {
    flexDirection: 'column',
    height: '25%',
    width: '80%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#404040',
    borderRadius: 27,
    padding: 4,
  },
  topPart: {
    flex: 0.5,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
    paddingVertical: 4,
  },
  middlePart: {
    flex: 1,
    width: '100%',
    textAlign: 'center',
    textAlignVertical: 'center',
    padding: 4,
    color: '#ffffff',
    fontSize: 16,
    marginVertical: 2,
  },
  bottomPart: {
    flex: 0.5,
    width: '100%',
    flexDirection: 'row',
    padding: 4,
    justifyContent: 'space-evenly',
  },
  alertTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#ffffff',
    fontSize: 31,
    fontFamily: 'Gruppo-Regular',
    padding: 2,
    marginHorizontal: 2,
  },
  alertMessage: {
    color: '#ffffff',
    textAlign: 'justify',
    fontSize: 27,
    padding: 2,
    fontFamily: 'Gruppo-Regular',
  },
  alertButton: {
    paddingHorizontal: 6,
    marginVertical: 4,
    borderRadius: 50,
    backgroundColor: Colors.mainColor,
    justifyContent: 'center',
  },
  alertButtonText: {
    fontSize: 23,
    fontFamily: 'Gruppo-Regular',
    color: '#ffffff',
  },
  view: {
    backgroundColor: 'black',
    width: '100%',
    height: '100%',
    position: 'absolute',
    opacity: 0.8,
  },
});

export const homeStyles = StyleSheet.create({
  container: {flex: 1},
  topView: {backgroundColor: Colors.mainColor, flex: 1},
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 12,
  },
  currentDate: {color: Colors.light, fontFamily: 'Gruppo-Regular'},
  hamburgerIcon1: {
    height: 2.5,
    backgroundColor: Colors.light,
    width: 35,
    borderRadius: 10,
  },
  hamburgerIcon2: {
    height: 2.5,
    backgroundColor: Colors.light,
    width: 25,
    borderRadius: 10,
    marginVertical: 8,
  },
  hamburgerIcon3: {
    height: 2.5,
    backgroundColor: Colors.light,
    width: 15,
    borderRadius: 10,
  },
  mainView1: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.mainColor,
    flex: 1,
    zIndex: 0,
  },
  inputArea: {
    flexDirection: 'row',
    height: 80,
    justifyContent: 'center',
  },
  convertToContainer: {
    justifyContent: 'center',
  },
  convertToBackground: {
    // backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'grey',
    height: 35,
    width: 35,
    elevation: 10,
    marginHorizontal: 10,
    // borderRadius: 20,
  },
  convertToPosition: {
    position: 'absolute',
  },
  flagSize: {
    height: 35,
    width: 35,
    // margin: 5,
  },
  inputWidth: {
    width: '35%',
  },
  inputStyle: {
    color: 'white',
    fontSize: 35,
    borderBottomWidth: 2,
    borderColor: 'white',
    padding: 15,
    fontFamily: 'Gruppo-Regular',
  },
  changeCurrencyPicker: {
    height: 50,
    width: 100,
    color: Colors.light,
  },
  changeCurrencyPickerTextFont: {fontFamily: 'Gruppo-Regular'},
  mainView2: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.light,
    flex: 1,
    zIndex: 0,
  },
  resultArea: {
    flexDirection: 'row',
    height: 80,
    justifyContent: 'center',
  },
  convertToFlagPosition: {
    justifyContent: 'center',
  },
  convertToFlagStyle: {
    // backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'grey',
    height: 35,
    width: 35,
    elevation: 10,
    marginHorizontal: 10,
    // borderRadius: 20,
  },
  loadingFlagPosition: {
    position: 'absolute',
  },
  inputStyleView2: {
    color: Colors.mainColor,
    fontSize: 35,
    borderBottomWidth: 2,
    borderColor: Colors.mainColor,
    padding: 15,
    fontFamily: 'Gruppo-Regular',
  },
  changeCurrencyPickerWidthView2: {width: '15%'},
  changeCurrencyPickerView2: {
    height: 50,
    width: 100,
    color: Colors.mainColor,
  },
  fetchingIconPostion: {position: 'absolute', bottom: '43%', right: '43%'},
  fetchingIconStyle: {
    backgroundColor: Colors.light,
    elevation: 20,
    height: 50,
    width: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
  },
  swapButtonPosition: {
    position: 'absolute',
    bottom: '43%',
    right: 20,
  },
  swapButtonStyle: {
    backgroundColor: Colors.light,
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    elevation: 10,
  },
});
